using Content.Client.Message;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI.Widgets;

/// <summary>
/// One device bound to the controller, shows what that device can do in the config
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AirlockDeviceRow : BoxContainer
{
    public Action<NetEntity, AirlockSide?>? OnDoorSideChanged;
    public Action<NetEntity, AirlockVentRole>? OnVentRolesChanged;

    private NetEntity _device;
    private AirlockVentRole _roles;

    public AirlockDeviceRow(AirlockDeviceEntry device)
    {
        RobustXamlLoader.Load(this);

        DoorSide.OnSideSelected += side => OnDoorSideChanged?.Invoke(_device, side);

        BindRole(VentACheck, AirlockVentRole.VentA);
        BindRole(SiphonACheck, AirlockVentRole.SiphonA);
        BindRole(VentBCheck, AirlockVentRole.VentB);
        BindRole(SiphonBCheck, AirlockVentRole.SiphonB);

        SetData(device);
    }

    private void BindRole(CheckBox check, AirlockVentRole role)
    {
        check.OnToggled += args =>
        {
            _roles = args.Pressed ? _roles | role : _roles & ~role;
            OnVentRolesChanged?.Invoke(_device, _roles);
        };
    }

    public void SetData(AirlockDeviceEntry device)
    {
        _device = device.Device;
        _roles = device.VentRoles;

        HeaderLabel.SetMarkup(Loc.GetString("airlock-controller-config-device-header",
            ("name", device.Name), ("address", device.Address)));

        DoorBox.Visible = device.IsDoor;
        DoorSide.SetSelection(device.DoorSide);

        VentBox.Visible = device.IsVent || device.IsScrubber;


        var canRelease = device.IsVent;
        VentACheck.Visible = canRelease;
        VentBCheck.Visible = canRelease;

        VentACheck.Pressed = (device.VentRoles & AirlockVentRole.VentA) != 0;
        SiphonACheck.Pressed = (device.VentRoles & AirlockVentRole.SiphonA) != 0;
        VentBCheck.Pressed = (device.VentRoles & AirlockVentRole.VentB) != 0;
        SiphonBCheck.Pressed = (device.VentRoles & AirlockVentRole.SiphonB) != 0;
    }
}
