using Content.Client.Message;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI.Widgets;

/// <summary>
/// One device bound to the controller, shows what that device can do in the config
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AirlockDeviceRow : BoxContainer
{
    public Action<NetEntity, AirlockSide?>? OnDoorSideChanged;
    public Action<NetEntity, AirlockSide?>? OnCyclerSideChanged;
    public Action<NetEntity, AirlockVentRole>? OnVentRolesChanged;

    private NetEntity _device;

    private bool _updating;

    public AirlockDeviceRow(AirlockDeviceEntry device, AirlockVentRole roles, AirlockSide? doorSide, AirlockSide? cyclerSide)
    {
        RobustXamlLoader.Load(this);

        DoorSide.OnSideSelected += side =>
        {
            if (!_updating)
                OnDoorSideChanged?.Invoke(_device, side);
        };

        CyclerSide.OnSideSelected += side =>
        {
            if (!_updating)
                OnCyclerSideChanged?.Invoke(_device, side);
        };

        BindRole(VentACheck);
        BindRole(SiphonACheck);
        BindRole(VentBCheck);
        BindRole(SiphonBCheck);

        SetData(device, roles, doorSide, cyclerSide);
    }

    private void BindRole(CheckBox check)
    {
        check.OnToggled += _ =>
        {
            if (!_updating)
                OnVentRolesChanged?.Invoke(_device, ReadRoles());
        };
    }

    /// <summary>
    ///     Built from the boxes
    /// </summary>
    private AirlockVentRole ReadRoles()
    {
        var roles = AirlockVentRole.None;

        if (VentACheck.Pressed)
            roles |= AirlockVentRole.VentA;

        if (SiphonACheck.Pressed)
            roles |= AirlockVentRole.SiphonA;

        if (VentBCheck.Pressed)
            roles |= AirlockVentRole.VentB;

        if (SiphonBCheck.Pressed)
            roles |= AirlockVentRole.SiphonB;

        return roles;
    }

    public void SetData(AirlockDeviceEntry device, AirlockVentRole roles, AirlockSide? doorSide, AirlockSide? cyclerSide)
    {
        _updating = true;

        try
        {
            _device = device.Device;

            HeaderLabel.SetMarkup(Loc.GetString("airlock-controller-config-device-header",
                ("name", device.Name), ("address", device.Address)));

            DoorBox.Visible = device.IsDoor;
            DoorSide.SetSelection(doorSide);

            CyclerBox.Visible = device.IsCycler;
            CyclerSide.SetSelection(cyclerSide);

            VentBox.Visible = device.IsVent || device.IsScrubber;

            // Scrubbers can only siphon
            var canRelease = device.IsVent;
            VentACheck.Visible = canRelease;
            VentBCheck.Visible = canRelease;

            VentACheck.Pressed = (roles & AirlockVentRole.VentA) != 0;
            SiphonACheck.Pressed = (roles & AirlockVentRole.SiphonA) != 0;
            VentBCheck.Pressed = (roles & AirlockVentRole.VentB) != 0;
            SiphonBCheck.Pressed = (roles & AirlockVentRole.SiphonB) != 0;
        }
        finally
        {
            _updating = false;
        }
    }
}
