using System.Linq;
using Content.Client.Atmos.AirlockController.UI.Widgets;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI;

/// <summary>
///     Everything the player can edit
/// </summary>
public sealed class AirlockConfigView
{
    public Dictionary<NetEntity, AirlockVentRole> VentRoles = new();
    public Dictionary<NetEntity, AirlockSide> DoorRoles = new();
    public Dictionary<NetEntity, AirlockSide> CyclerRoles = new();
    public NetEntity? TargetSensorA;
    public NetEntity? TargetSensorB;
    public float PresetPressureA;
    public float PresetPressureB;
    public bool MaintenanceMode;
}

[GenerateTypedNameReferences]
public sealed partial class AirlockControllerConfigWindow : FancyWindow
{
    public event Action<NetEntity, AirlockVentRole>? VentRolesChanged;
    public event Action<NetEntity, AirlockSide?>? DoorSideChanged;
    public event Action<NetEntity, AirlockSide?>? CyclerSideChanged;
    public event Action<AirlockSide, NetEntity?>? TargetSensorChanged;
    public event Action<AirlockSide, float>? PresetChanged;
    public event Action<bool>? MaintenanceChanged;
    public event Action<AirlockSide>? ForceSideRequested;

    private readonly Dictionary<NetEntity, AirlockDeviceRow> _rows = new();

    private const int CustomId = -1;

    /// <summary>
    ///     Sensor picker order for A and B sides
    /// </summary>
    private List<NetEntity> _options = new();

    private bool _pickersBuilt;

    private AirlockControllerConfigUiState? _telemetry;
    private AirlockConfigView? _config;

    private bool _updating;

    public AirlockControllerConfigWindow()
    {
        RobustXamlLoader.Load(this);

        CPresetHint.SetMarkup(Loc.GetString("airlock-controller-config-preset-hint"));

        CPresetA.IsValid += value => value >= 0;
        CPresetB.IsValid += value => value >= 0;

        CPresetA.OnValueChanged += args => Send(() => PresetChanged?.Invoke(AirlockSide.A, args.Value));
        CPresetB.OnValueChanged += args => Send(() => PresetChanged?.Invoke(AirlockSide.B, args.Value));

        CMaintenanceCheck.OnToggled += args => Send(() => MaintenanceChanged?.Invoke(args.Pressed));

        CForceAButton.OnPressed += _ => Send(() => ForceSideRequested?.Invoke(AirlockSide.A));
        CForceBButton.OnPressed += _ => Send(() => ForceSideRequested?.Invoke(AirlockSide.B));

        BindSensorPicker(CSensorA, AirlockSide.A);
        BindSensorPicker(CSensorB, AirlockSide.B);
    }

    private void Send(Action send)
    {
        if (_updating)
            return;

        send();
    }

    private void BindSensorPicker(OptionButton picker, AirlockSide side)
    {
        picker.OnItemSelected += args => Send(() =>
        {
            picker.TrySelectId(args.Id);
            TargetSensorChanged?.Invoke(side, args.Id == CustomId ? null : _options[args.Id]);
        });
    }

    /// <summary>
    ///     Server-owned readings and device identity.
    /// </summary>
    public void SetTelemetry(AirlockControllerConfigUiState state)
    {
        _telemetry = state;
        Refresh();
    }

    /// <summary>
    ///     Predicted config
    /// </summary>
    public void SetConfig(AirlockConfigView config)
    {
        _config = config;
        Refresh();
    }

    private void Refresh()
    {
        if (_telemetry is not { } state || _config is not { } config)
            return;

        _updating = true;

        try
        {
            Repaint(state, config);
        }
        finally
        {
            _updating = false;
        }
    }

    private void Repaint(AirlockControllerConfigUiState state, AirlockConfigView config)
    {
        RebuildSensorPickers(state, config);

        ApplyPreset(CPresetA, CSensorALabel, config.PresetPressureA, config.TargetSensorA, state.TargetPressureA);
        ApplyPreset(CPresetB, CSensorBLabel, config.PresetPressureB, config.TargetSensorB, state.TargetPressureB);

        CMaintenanceCheck.Pressed = config.MaintenanceMode;
        CAddressLabel.SetMarkup(state.Address);
        CDoorsLabel.SetMarkup(state.DoorCount.ToString());
        CChamberSensorsLabel.SetMarkup(state.ChamberSensorCount.ToString());

        var onA = state.CurrentSide == AirlockSide.A;

        CCurrentSideLabel.SetMarkup(Loc.GetString(onA
            ? "airlock-controller-side-a"
            : "airlock-controller-side-b"));

        // Forcing the side you're already on does nothing
        CForceAButton.Disabled = onA;
        CForceBButton.Disabled = !onA;

        var seen = new HashSet<NetEntity>();

        foreach (var device in state.Devices)
        {
            seen.Add(device.Device);

            config.VentRoles.TryGetValue(device.Device, out var roles);
            var side = config.DoorRoles.TryGetValue(device.Device, out var assigned) ? assigned : (AirlockSide?)null;
            var cycler = config.CyclerRoles.TryGetValue(device.Device, out var calls) ? calls : (AirlockSide?)null;

            if (_rows.TryGetValue(device.Device, out var row))
            {
                row.SetData(device, roles, side, cycler);
                continue;
            }

            row = new AirlockDeviceRow(device, roles, side, cycler);
            row.OnDoorSideChanged += (uid, doorSide) => DoorSideChanged?.Invoke(uid, doorSide);
            row.OnCyclerSideChanged += (uid, cyclerSide) => CyclerSideChanged?.Invoke(uid, cyclerSide);
            row.OnVentRolesChanged += (uid, ventRoles) => VentRolesChanged?.Invoke(uid, ventRoles);

            _rows[device.Device] = row;
            CDeviceContainer.AddChild(row);
        }

        foreach (var device in _rows.Keys.ToArray())
        {
            if (seen.Contains(device))
                continue;

            CDeviceContainer.RemoveChild(_rows[device]);
            _rows.Remove(device);
        }
    }

    /// <summary>
    ///     Custom above pickers, sensors in list order
    /// </summary>
    private void RebuildSensorPickers(AirlockControllerConfigUiState state, AirlockConfigView config)
    {
        var changed = !_pickersBuilt
                      || _options.Count != state.Sensors.Count
                      || _options.Where((device, i) => device != state.Sensors[i].Device).Any();

        if (changed)
        {
            _options = state.Sensors.Select(sensor => sensor.Device).ToList();

            foreach (var picker in new[] { CSensorA, CSensorB })
            {
                picker.Clear();
                picker.AddItem(Loc.GetString("airlock-controller-config-sensor-custom"), CustomId);

                for (var i = 0; i < state.Sensors.Count; i++)
                {
                    picker.AddItem(state.Sensors[i].Name, i);
                }
            }

            _pickersBuilt = true;
        }

        SelectSensor(CSensorA, config.TargetSensorA);
        SelectSensor(CSensorB, config.TargetSensorB);
    }

    private void SelectSensor(OptionButton picker, NetEntity? selected)
    {
        var index = selected is { } device ? _options.IndexOf(device) : -1;

        if (!picker.TrySelectId(index < 0 ? CustomId : index))
            picker.TrySelectId(CustomId);
    }

    private static void ApplyPreset(
        FloatSpinBox box,
        RichTextLabel label,
        float pressure,
        NetEntity? sensor,
        float? reading)
    {
        var following = sensor != null;

        // Hide input field when sensor mode, and vice versa
        box.Visible = !following;
        label.Visible = following;

        if (following)
        {
            // The pick is predicted, the reading isn't, placeholder it
            label.SetMarkup(reading is { } value
                ? Loc.GetString("airlock-controller-ui-pressure-value", ("pressure", $"{value:0.#}"))
                : Loc.GetString("airlock-controller-config-sensor-pending"));
            return;
        }

        // don't overwrite typing
        if (box.HasKeyboardFocus())
            return;

        box.Value = pressure;
    }
}
