using System.Linq;
using Content.Client.Atmos.AirlockController.UI.Widgets;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI;

[GenerateTypedNameReferences]
public sealed partial class AirlockControllerConfigWindow : FancyWindow
{
    public event Action<NetEntity, AirlockVentRole>? VentRolesChanged;
    public event Action<NetEntity, AirlockSide?>? DoorSideChanged;
    public event Action<AirlockSide, NetEntity?>? TargetSensorChanged;
    public event Action<AirlockSide, float>? PresetChanged;
    public event Action<bool>? MaintenanceChanged;
    public event Action<AirlockSide>? ForceSideRequested;

    private readonly Dictionary<NetEntity, AirlockDeviceRow> _rows = new();

    public AirlockControllerConfigWindow()
    {
        RobustXamlLoader.Load(this);

        CPresetHint.SetMarkup(Loc.GetString("airlock-controller-config-preset-hint"));

        CPresetA.IsValid += value => value >= 0;
        CPresetB.IsValid += value => value >= 0;

        CPresetA.OnValueChanged += args => PresetChanged?.Invoke(AirlockSide.A, args.Value);
        CPresetB.OnValueChanged += args => PresetChanged?.Invoke(AirlockSide.B, args.Value);

        CMaintenanceCheck.OnToggled += args => MaintenanceChanged?.Invoke(args.Pressed);

        CForceAButton.OnPressed += _ => ForceSideRequested?.Invoke(AirlockSide.A);
        CForceBButton.OnPressed += _ => ForceSideRequested?.Invoke(AirlockSide.B);
    }

    public void UpdateState(AirlockControllerConfigUiState state)
    {
        ApplyPreset(CPresetA, CSensorALabel, state.PresetPressureA, state.TargetSensorNameA);
        ApplyPreset(CPresetB, CSensorBLabel, state.PresetPressureB, state.TargetSensorNameB);

        CMaintenanceCheck.Pressed = state.MaintenanceMode;
        CAddressLabel.SetMarkup(state.Address);
        CDoorsLabel.SetMarkup(state.DoorCount.ToString());

        var onA = state.CurrentSide == AirlockSide.A;

        CCurrentSideLabel.SetMarkup(Loc.GetString(onA
            ? "airlock-controller-side-a"
            : "airlock-controller-side-b"));

        // Forcing the side you're already on does nothing
        CForceAButton.Disabled = onA;
        CForceBButton.Disabled = !onA;

        var seen = new HashSet<NetEntity>();

        foreach (var device in state.Devices)
        {
            seen.Add(device.Device);

            if (_rows.TryGetValue(device.Device, out var row))
            {
                row.SetData(device);
                continue;
            }

            row = new AirlockDeviceRow(device);
            row.OnDoorSideChanged += (uid, side) => DoorSideChanged?.Invoke(uid, side);
            row.OnVentRolesChanged += (uid, roles) => VentRolesChanged?.Invoke(uid, roles);
            row.OnTargetSensorChanged += (side, uid) => TargetSensorChanged?.Invoke(side, uid);

            _rows[device.Device] = row;
            CDeviceContainer.AddChild(row);
        }

        foreach (var device in _rows.Keys.ToArray())
        {
            if (seen.Contains(device))
                continue;

            CDeviceContainer.RemoveChild(_rows[device]);
            _rows.Remove(device);
        }
    }

    private static void ApplyPreset(FloatSpinBox box, RichTextLabel label, float pressure, string? sensorName)
    {
        var following = sensorName != null;

        // Hide input field when sensor mode, and vice versa
        box.Visible = !following;
        label.Visible = following;

        if (following)
        {
            label.SetMarkup(sensorName!);
            return;
        }

        // don't overwrite player typing
        if (box.HasKeyboardFocus())
            return;

        box.Value = pressure;
    }
}
