using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI;

[GenerateTypedNameReferences]
public sealed partial class AirlockControllerWindow : FancyWindow
{
    public event Action<AirlockSide>? CycleRequested;
    public event Action? CancelRequested;
    public event Action? ConfigRequested;

    public AirlockControllerWindow()
    {
        RobustXamlLoader.Load(this);

        CCycleAButton.OnPressed += _ => CycleRequested?.Invoke(AirlockSide.A);
        CCycleBButton.OnPressed += _ => CycleRequested?.Invoke(AirlockSide.B);
        CCancelButton.OnPressed += _ => CancelRequested?.Invoke();
        CConfigButton.OnPressed += _ => ConfigRequested?.Invoke();
    }

    public void SetEntity(EntityUid uid)
    {
        EntityView.SetEntity(uid);
    }

    public void SetConfigAllowed(bool allowed)
    {
        CConfigButton.Disabled = !allowed;
    }

    public void UpdateState(AirlockControllerUiState state)
    {
        var idle = state.State == AirlockCycleState.Idle;

        CStateLabel.SetMarkup(Loc.GetString(StateKey(state.State)));
        CSideLabel.SetMarkup(Loc.GetString(SideKey(state.CurrentSide)));
        CPressureLabel.SetMarkup(state.ChamberPressure is { } pressure
            ? Loc.GetString("airlock-controller-ui-pressure-value", ("pressure", $"{pressure:0.#}"))
            : Loc.GetString("airlock-controller-ui-pressure-unknown"));

        // A stall reports the problem without state change
        CStallStripe.Visible = state.StallReason != null;
        if (state.StallReason is { } reason)
            CStallLabel.SetMarkup(Loc.GetString(StallKey(reason)));

        // You can only cycle to the side you aren't already at
        CCycleAButton.Disabled = !idle || state.CurrentSide == AirlockSide.A || state.MaintenanceMode;
        CCycleBButton.Disabled = !idle || state.CurrentSide == AirlockSide.B || state.MaintenanceMode;

        CCancelButton.Disabled = idle || state.MaintenanceMode;
        CCancelButton.Text = Loc.GetString(state.CancelRequested
            ? "airlock-controller-ui-cancel-emergency"
            : "airlock-controller-ui-cancel");
    }

    private static string StateKey(AirlockCycleState state) => state switch
    {
        AirlockCycleState.Idle => "airlock-controller-state-idle",
        AirlockCycleState.Sealing => "airlock-controller-state-sealing",
        AirlockCycleState.Evacuating => "airlock-controller-state-evacuating",
        AirlockCycleState.Filling => "airlock-controller-state-filling",
        AirlockCycleState.Unsealing => "airlock-controller-state-unsealing",
        _ => "airlock-controller-state-idle",
    };

    private static string SideKey(AirlockSide side) => side == AirlockSide.A
        ? "airlock-controller-side-a"
        : "airlock-controller-side-b";

    private static string StallKey(AirlockStallReason reason) => reason switch
    {
        AirlockStallReason.NoUsableVent => "airlock-controller-stall-no-vent",
        AirlockStallReason.NoSensors => "airlock-controller-stall-no-sensors",
        AirlockStallReason.NotProgressing => "airlock-controller-stall-not-progressing",
        AirlockStallReason.SealLost => "airlock-controller-stall-seal-lost",
        AirlockStallReason.NotSealing => "airlock-controller-stall-not-sealing",
        AirlockStallReason.MissingDoors => "airlock-controller-stall-missing-doors",
        AirlockStallReason.NotOpening => "airlock-controller-stall-not-opening",
        _ => "airlock-controller-stall-not-progressing",
    };
}
