using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.AirlockController;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.AirlockController.UI;

[GenerateTypedNameReferences]
public sealed partial class AirlockCyclerWindow : FancyWindow
{
    public event Action? CycleRequested;

    public AirlockCyclerWindow()
    {
        RobustXamlLoader.Load(this);

        CCycleButton.OnPressed += _ => CycleRequested?.Invoke();
    }

    public void SetEntity(EntityUid uid)
    {
        EntityView.SetEntity(uid);
    }

    public void UpdateState(AirlockCyclerUiState state)
    {
        var status = state.Status;
        var idle = status.State == AirlockCycleState.Idle;

        CStateLabel.SetMarkup(Loc.GetString(state.Bound
            ? AirlockControllerLocale.StateKey(status.State)
            : "airlock-cycler-ui-unbound"));

        CSideLabel.SetMarkup(Loc.GetString(AirlockControllerLocale.SideKey(status.Side)));
        CPressureLabel.SetMarkup(state.ChamberPressure is { } pressure
            ? Loc.GetString("airlock-controller-ui-pressure-value", ("pressure", $"{pressure:0.#}"))
            : Loc.GetString("airlock-controller-ui-pressure-unknown"));

        CStallStripe.Visible = status.Stall != null;
        if (status.Stall is { } reason)
            CStallLabel.SetMarkup(Loc.GetString(AirlockControllerLocale.StallKey(reason)));

        // Nothing to call for if the chamber is already here
        CCycleButton.Disabled = !state.Bound
                                || !idle
                                || status.Maintenance
                                || status.Side == state.Side;

        CCycleButton.Text = Loc.GetString(state.Side == AirlockSide.A
            ? "airlock-controller-ui-cycle-a"
            : "airlock-controller-ui-cycle-b");
    }
}
